CC = cl
CFLAGS += /Zi /MTd
CFLAGS += /I"%JAVA_HOME%"\include /I"%JAVA_HOME%"\include\win32
CFLAGS += /I"%LUA_HOME%"\include
LDFLAGS += /LIBPATH:"%LUA_HOME%"\lib

.SUFFIXES: .obj .c
.c.obj:
	$(CC) $(CFLAGS) /c $<

yt.dll: yt.obj lua_interface.obj lua_java.obj jni_util.obj
	link /DLL /DEBUG /OUT:yt.dll /INCREMENTAL:NO $(LDFLAGS) $^ lua52.lib

clean:
	-rm yt.obj lua_interface.obj lua_java.obj jni_util.obj yt.dll
